name: offertelavoroflutter_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^1.3.0
  flutter_bloc: ^8.1.2
  flutter_secure_storage: ^8.0.0
  pine: ^1.0.2
  equatable: ^2.0.5
  dio: ^5.1.1
  font_awesome_flutter: ^10.4.0
  provider: ^6.0.5
  pretty_dio_logger: ^1.3.1
  hydrated_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  http_mock_adapter: ^0.4.2
  data_fixture_dart: ^2.2.0
  mockito: ^5.4.0
  bloc_test: ^9.1.1

flutter:

  uses-material-design: true

  # assets:
  #   - assets/images

  fonts:
    - family: Montserrat
      fonts: 
        - asset: assets/font/Montserrat-Regular.ttf
        - asset: assets/font/Montserrat-Italic.ttf
          style: italic
        - asset: assets/font/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/font/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Montserrat-Light.ttf
          weight: 300
        - asset: assets/font/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/font/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/font/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/font/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/font/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Montserrat-Black.ttf
          weight: 900

